info:
  component: Cloud Native Eureka Server

server:
  port: 8761

management:
  context-path: /admin

endpoints:
  info:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true
    sensitive: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false